### ISSUE TITLE
Idea: See if there are not-well-known pandoc features that are worth showing

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#106]
Rmarkdown is powerful because it uses pandoc for conversion, and pandoc is powerful. The documentation if full of trick for customisation - rmarkdown has made some choices but you can easily customize based on the [great pandoc manual](http://pandoc.org/MANUAL.html) that [everyone should read](https://yihui.name/en/2017/11/thanks-tj-mahr/). 

Showing some example of advanced usage could help promote this yihui motto. It could be a good source of recipes too. 

Examples  :
- [ ] link attributes (https://yihui.name/en/2018/09/target-blank/)
- [ ] `grid_tables` (#105)
- [ ] pandoc args (#107)
- [ ] table caption ([SO question](https://stackoverflow.com/questions/33965560/r-markdown-table-with-a-caption/33965888#33965888))
- [x] Image sizing with [`link_attributes`](http://pandoc.org/MANUAL.html#extension-link_attributes) (related to #17 and this [SO question](https://stackoverflow.com/questions/25166624/insert-picture-table-in-r-markdown))
- [x] `link-as-notes` (#204)

**Comment by dr-harper** [comment]
This manual has come in useful so many times. I will read through it again and see if there are any other key details that I think would be useful to include

**Comment by cderv** [comment]
pandoc raw block added in 5aef0af258e8f5f97bc92d76908b25b220594832 based on this [SO Question](https://stackoverflow.com/q/61236949/559676)

**Comment by fkohrt** [comment]
Some other suggestions which I discovered late:

- [no-author citations](https://pandoc.org/MANUAL.html#citations) such as `Smith says blah [-@smith04].`
- `csquotes` metadata field, hidden [very well](https://pandoc.org/MANUAL.html#creating-a-pdf), which, in combination with `extra_dependencies: ["csquotes"]`, makes LaTeX honor the `lang`uage. What's more, localized quotation marks inside HTML require the [`pandoc-quotes.lua`](https://github.com/pandoc/lua-filters/tree/master/pandoc-quotes.lua) filter.
